server:
  port: 8069  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  profiles:
    active: local
  application:
    name: user-service
tj:
  secret: 1oEYCJ7RWcj9ygfsVfw8L8MUj94aLtKZxqd3aB2x6Yg
  swagger:
    enable: true
    enableResponseWrap: true
    package-path: com.interview.user.controller
  auth:
    resource:
      enable: false
      excludeLoginPaths:
        - /students/register
        - /users/detail/{isStaff}
        - /users/list
        - GET:/users/{id}
        - /users/{id}/type
        - /users/ids
        - /users/me
  jdbc:
    database: user_db
