server:
  port: 8070  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  rabbitmq:
    host: 192.168.150.101
    port: 5672
    username: tjxt     # 默认用户名（如果没改）
    password: 123321      # 默认密码（如果没改）
    virtual-host: /      # 默认 vhost（可选）
  profiles:
    active: local
  application:
    name: resume-service
tj:
  secret: 1oEYCJ7RWcj9ygfsVfw8L8MUj94aLtKZxqd3aB2x6Yg
  swagger:
    enable: true
    enableResponseWrap: true
  auth:
    resource:
      enable: false
      excludeLoginPaths:

  jdbc:
    database: resume_db
